spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/umovies
    username: ubots
    password: ubots
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
